version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=billing
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=billing
    ports:
      - 5434:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6377:6379

  worker:
    build: .
    depends_on:
      - redis
      - db
      - rabbitmq
    volumes:
      - ./src:/app/src
    command: bash -c "cd src/ && celery -A billing.settings.celery worker -l info"
    env_file:
      - .env

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://myuser:mypass@rabbitmq:5672/myvhost
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - worker

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "8031:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_VHOST=myvhost

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "cd src && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - 8010:8000
    env_file:
      - .env
